from pathlib import Path
import shutil
import unittest

import pandas as pd

from buhinvest_analize import buhinvest_reports


class BuhinvestReportsTests(unittest.TestCase):
    def test_compute_real_capital_returns_uses_previous_account_equity(self):
        df = pd.DataFrame(
            {
                "Дата": pd.to_datetime(["2026-04-01", "2026-04-02", "2026-04-03"]),
                "Вводы": [0.0, 500.0, 0.0],
                "Всего на счетах": [10_100.0, 10_800.0, 11_100.0],
                "Profit/Loss к предыдущему": [100.0, 200.0, 300.0],
            }
        )

        returns = buhinvest_reports.compute_real_capital_returns(df)

        expected = pd.Series(
            [0.0, 200.0 / 10_600.0, 300.0 / 10_800.0],
            index=df["Дата"],
        )
        pd.testing.assert_series_equal(
            returns,
            expected,
            check_names=False,
            atol=1e-9,
            rtol=1e-9,
        )

    def test_compute_real_capital_returns_uses_cash_adjusted_base_on_flow_day(self):
        df = pd.DataFrame(
            {
                "Дата": pd.to_datetime(["2026-04-01", "2026-04-02"]),
                "Вводы": [0.0, 2_000.0],
                "Всего на счетах": [10_000.0, 12_250.0],
                "Profit/Loss к предыдущему": [0.0, 250.0],
            }
        )

        returns = buhinvest_reports.compute_real_capital_returns(df)

        expected = pd.Series([0.0, 250.0 / 12_000.0], index=df["Дата"])
        pd.testing.assert_series_equal(
            returns,
            expected,
            check_names=False,
            atol=1e-9,
            rtol=1e-9,
        )

    def test_build_qs_report_writes_html_tearsheet(self):
        df = pd.DataFrame(
            {
                "Дата": pd.to_datetime(["2026-04-01", "2026-04-02", "2026-04-03"]),
                "Вводы": [0.0, 0.0, 0.0],
                "Всего на счетах": [10_100.0, 10_000.0, 10_250.0],
                "Profit/Loss к предыдущему": [100.0, -100.0, 250.0],
            }
        )
        returns = buhinvest_reports.compute_real_capital_returns(df)

        tmp_dir = Path(__file__).resolve().parent / "_tmp_qs_report"
        if tmp_dir.exists():
            shutil.rmtree(tmp_dir)
        tmp_dir.mkdir(parents=True)
        try:
            output_html = tmp_dir / "pl_buhinvest_interactive_qs.html"
            buhinvest_reports.build_qs_report(
                returns=returns,
                output_html=output_html,
                title="Buhinvest QuantStats",
            )

            self.assertTrue(output_html.exists())
            html = output_html.read_text(encoding="utf-8")
            self.assertIn("generated by QuantStats", html)
            self.assertIn("Buhinvest QuantStats", html)
        finally:
            shutil.rmtree(tmp_dir)


if __name__ == "__main__":
    unittest.main()
